# Generated by Django 5.2.6 on 2025-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
