# Generated by Django 5.2.6 on 2025-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_favoritename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritename',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='favoritename',
            name='category',
        ),
        migrations.AddField(
            model_name='favoritename',
            name='race',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
