# Generated by Django 5.2.6 on 2025-09-24 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_remove_favoritename_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritename',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
