# Generated by Django 5.2.6 on 2026-03-11 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_favoritename_added_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fantasyname',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fantasy Name', 'verbose_name_plural': 'Fantasy Names'},
        ),
        migrations.AlterModelOptions(
            name='favoritename',
            options={'verbose_name': 'Favorite Name', 'verbose_name_plural': 'Favorite Names'},
        ),
        migrations.AlterModelOptions(
            name='namecategory',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='fantasyname',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='generator.namecategory'),
        ),
        migrations.AlterField(
            model_name='favoritename',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritename',
            unique_together={('user', 'name')},
        ),
    ]
